---
- name: generate test folder structure
  hosts: redhatclient
  tasks:
  - name: show message test
    debug:
      msg: folders are "{{ item.name}}", files are "{{ item.path }}"
    loop: "{{ servicefiles }}"

  - name: generate folders
    file:
      path: "{{item.path}}"
      state: directory
      owner: zhengj 
      group: zhengj 
      mode: "0755"
    loop: "{{servicefolders}}"

  - name: generate files
    file:
      path: "{{item}}"
      owner: zhengj 
      group: zhengj
      state: touch
      mode: "0755"
    loop: "{{servicefiles}}"